language: node_js
node_js:
  - "12"

cache:
  directories:
    - "node_modules"

install:
  - yarn install

script:
  - yarn docs:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .build/docs
  target_branch: gh-pages
  on:
    branch: main